services:
  - type: worker
    name: python
    env: python
    region: Oregon
    plan: free
    buildCommand: "pip install proxy.py"
    startCommand: "proxy --hostname 0.0.0.0 --port 8080"
    envVars:
    - key: PYTHON_VERSION
      value: 3.10.9
